# Generated by Django 4.2.6 on 2023-11-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentprofile',
            name='service',
            field=models.TextField(blank=True, default='', help_text='Enter the services you are interested in.', null=True, verbose_name='Services'),
        ),
    ]
