# Generated by Django 4.2.7 on 2023-11-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimprovementrequest',
            name='description',
        ),
        migrations.AlterField(
            model_name='serviceimprovementrequest',
            name='service',
            field=models.TextField(),
        ),
    ]
