# Generated by Django 4.2.7 on 2023-11-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_serviceimprovementrequest_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countyservices',
            name='county',
        ),
        migrations.RemoveField(
            model_name='countyservices',
            name='services',
        ),
    ]
